package example;

/**
 * @author Barry DeZonia
 */
class LorenzAttractor {

	/*
	 * Visualizing the Lorenz attractor has been implemented as an example to show
	 * some of what Zorbage can do. It uses jMonkeyEngine3 to walk through the
	 * Lorenz attractor viewing points generated by Zorbage's differential equation
	 * solver. See more at the following link:
	 * 
	 *   https://github.com/bdezonia/zorbage/blob/master/example/lorenz/Main.java
	 */
}
