/*
 * Zorbage: an algebraic data hierarchy for use in numeric processing.
 *
 * Copyright (c) 2016-2021 Barry DeZonia All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 * 
 * Redistributions of source code must retain the above copyright notice, this list
 * of conditions and the following disclaimer.
 * 
 * Redistributions in binary form must reproduce the above copyright notice, this
 * list of conditions and the following disclaimer in the documentation and/or other
 * materials provided with the distribution.
 * 
 * Neither the name of the <copyright holder> nor the names of its contributors may
 * be used to endorse or promote products derived from this software without specific
 * prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
 * DAMAGE.
 */
package nom.bdezonia.zorbage.algorithm;

import nom.bdezonia.zorbage.algebra.Algebra;
import nom.bdezonia.zorbage.algebra.Multiplication;
import nom.bdezonia.zorbage.algebra.SetOctonion;
import nom.bdezonia.zorbage.algebra.Trigonometric;

/* Adapted from code in the Boost libraries
 * 
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
 * 
 */

/**
 * 
 * @author Barry DeZonia
 *
 */
public class OctonionMultiPolar {

	private OctonionMultiPolar() { }
	
	/**
	 * 
	 * @param rho1
	 * @param theta1
	 * @param rho2
	 * @param theta2
	 * @param rho3
	 * @param theta3
	 * @param rho4
	 * @param theta4
	 * @param out
	 */
	public static <T extends Algebra<T,U> & Trigonometric<U> & Multiplication<U>, U>
		void compute(T alg, U rho1, U theta1, U rho2, U theta2, U rho3, U theta3, U rho4, U theta4, SetOctonion<U> out)
	{
		U tmpTh1C = alg.construct();
		U tmpTh1S = alg.construct();
		U tmpTh2C = alg.construct();
		U tmpTh2S = alg.construct();
		U tmpTh3C = alg.construct();
		U tmpTh3S = alg.construct();
		U tmpTh4C = alg.construct();
		U tmpTh4S = alg.construct();

		alg.sinAndCos().call(theta1, tmpTh1S, tmpTh1C);
		alg.sinAndCos().call(theta2, tmpTh2S, tmpTh2C);
		alg.sinAndCos().call(theta3, tmpTh3S, tmpTh3C);
		alg.sinAndCos().call(theta4, tmpTh4S, tmpTh4C);

		U r = alg.construct();
		U i = alg.construct();
		U j = alg.construct();
		U k = alg.construct();
		U l = alg.construct();
		U i0 = alg.construct();
		U j0 = alg.construct();
		U k0 = alg.construct();
		
		alg.multiply().call(rho1, tmpTh1C, r);
		alg.multiply().call(rho1, tmpTh1S, i);
		alg.multiply().call(rho2, tmpTh2C, j);
		alg.multiply().call(rho2, tmpTh2S, k);
		alg.multiply().call(rho3, tmpTh3C, l);
		alg.multiply().call(rho3, tmpTh3S, i0);
		alg.multiply().call(rho4, tmpTh4C, j0);
		alg.multiply().call(rho4, tmpTh4S, k0);
		
		out.setR(r);
		out.setI(i);
		out.setJ(j);
		out.setK(k);
		out.setL(l);
		out.setI0(i0);
		out.setJ0(j0);
		out.setK0(k0);
	}

}
